### ISSUE TITLE
container.Cities.All

### ISSUE THREAD

**Issue by IanaKhitsko** [ChumakMike/Practice_1#10]
https://github.com/ChumakMike/Practice_1/blob/b3670526a67f37039a87a0c038d77251925d336c/lab1/Services/MapService.cs#L87

Cna we use container.Cities.All here with lambda?

**Comment by ChumakMike** [comment]
All() statement from LINQ is used now [2768982](https://github.com/ChumakMike/Practice_1/commit/2768982304785913e8a8862891585cbb6d152166)
