### ISSUE TITLE
Use properties instead of fields for public attributes

### ISSUE THREAD

**Issue by artyoda05** [ChumakMike/Practice_1#3]
https://github.com/ChumakMike/Practice_1/blob/b4ec69423d4b002f64dacf60ac0bba7269507d1b/lab1/Models/Map.cs#L7

https://github.com/ChumakMike/Practice_1/blob/b4ec69423d4b002f64dacf60ac0bba7269507d1b/lab1/Models/Map.cs#L14-L18

**Comment by ChumakMike** [comment]
- fixed
