### ISSUE TITLE
What if the Constants.MaxNameLength will be changed? 

### ISSUE THREAD

**Issue by IanaKhitsko** [ChumakMike/Practice_1#6]
https://github.com/ChumakMike/Practice_1/blob/b3670526a67f37039a87a0c038d77251925d336c/lab1/Validators/CountryValidator.cs#L24

What if the Constants.MaxNameLength will be changed?

**Comment by ChumakMike** [comment]
This bug was fixed [2768982](https://github.com/ChumakMike/Practice_1/commit/2768982304785913e8a8862891585cbb6d152166)
