### ISSUE TITLE
Const?

### ISSUE THREAD

**Issue by IanaKhitsko** [ChumakMike/Practice_1#7]
https://github.com/ChumakMike/Practice_1/blob/b3670526a67f37039a87a0c038d77251925d336c/lab1/Services/CityService.cs#L48

1000 can be const

**Comment by ChumakMike** [comment]
Magic number was removed to constants [2768982](https://github.com/ChumakMike/Practice_1/commit/2768982304785913e8a8862891585cbb6d152166)
