### ISSUE TITLE
Countries.Any

### ISSUE THREAD

**Issue by IanaKhitsko** [ChumakMike/Practice_1#9]
https://github.com/ChumakMike/Practice_1/blob/b3670526a67f37039a87a0c038d77251925d336c/lab1/Services/CityService.cs#L25

Can we use countries.Any wth some lambda here?

**Comment by ChumakMike** [comment]
It is better to use All(), the code was improved [2768982](https://github.com/ChumakMike/Practice_1/commit/2768982304785913e8a8862891585cbb6d152166)
